import sys
import subprocess
import shutil
from pathlib import Path

# Configuration
SCRIPT_DIR = Path(__file__).parent
JLINK_SCRIPTS_DIR = SCRIPT_DIR
OEMIROT_DIR = SCRIPT_DIR.parent
CUBE_FW_PATH = SCRIPT_DIR / "../../../../.."

DEVICE = "STM32H573IIKxQ"
INTERFACE = "SWD"
SPEED = "4000"

OEMIROT_BOOT_BIN = CUBE_FW_PATH / "Projects/STM32H573I-DK/Applications/ROT/OEMiROT_Boot/Binary/OEMiROT_Boot.bin"
APPLI_DIR = CUBE_FW_PATH / "Projects/STM32H573I-DK/Applications/ROT/OEMiROT_Appli"
DA_OBKEY = OEMIROT_DIR / "../DA/Binary/DA_Config.obk"
OEMIROT_CONFIG_OBKEY = OEMIROT_DIR / "Binary/OEMiRoT_Config.obk"
OEMIROT_DATA_OBKEY = OEMIROT_DIR / "Binary/OEMiRoT_Data.obk"

JLINK_EXE = "JLinkExe"
DEVPRO_EXE = "DevProExe"
DEVPRO_SCRIPT = "PCode_DevPro_ST_STM32H5.pex"

def print_error(msg):
    print(f"ERROR: {msg}")

def run_jlink_script(script_name, action_str):
    script_path = JLINK_SCRIPTS_DIR / script_name
    print(action_str)

    cmd = [
        JLINK_EXE,
        "-device", DEVICE,
        "-if", INTERFACE,
        "-speed", SPEED,
        "-autoconnect", "1",
        "-CommandFile", str(script_path)
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode != 0 or "Cannot connect" in result.stdout or "Failed" in result.stdout:
            print_error("J-Link command failed")
            print(result.stdout)
            if result.stderr:
                print(result.stderr)
            return False

        print("DONE")
        return True
    except subprocess.TimeoutExpired:
        print_error(f"Timeout executing {script_name}")
        return False
    except Exception as e:
        print_error(f"Error executing {script_name}: {e}")
        return False

def run_devpro_operation(operation, config_vals=None):
    cmd = [
        DEVPRO_EXE,
        "-operation", operation,
        "-if", INTERFACE,
        "-speed", SPEED,
        "-ScriptFile", DEVPRO_SCRIPT,
    ]

    if config_vals:
        for key, value in config_vals.items():
            cmd.extend(["-SetConfigVal", f"{key}={value}"])

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode != 0:
            print_error(f"DevPro operation failed: {operation}")
            if result.stdout:
                print(result.stdout)
            if result.stderr:
                print(result.stderr)
            return False
        return True
    except subprocess.TimeoutExpired:
        print_error(f"Timeout executing DevPro operation: {operation}")
        return False
    except Exception as e:
        print_error(f"Error executing DevPro operation {operation}: {e}")
        return False

def program_obkeys_with_devpro():
    print("Discovering product state (DevPro)")
    if not run_devpro_operation("DbgAuthDiscover"):
        return False

    print("Setting product state to PROVISIONING (DevPro)")
    if not run_devpro_operation(DEVPRO_EXE, "SetDeviceState", {"ProdState": "PROVISIONING"}):
        return False

    obk_files = [
        DA_OBKEY,
        OEMIROT_CONFIG_OBKEY,
        OEMIROT_DATA_OBKEY,
    ]

    for obk_file in obk_files:
        print(f"Provisioning OBK with DevPro: {obk_file}")
        if not run_devpro_operation(DEVPRO_EXE, "DbgAuthProvision", {"DataFile": str(obk_file)}):
            return False

    return True

def generate_option_bytes_script():
    ob_config = {
        "0x40022050": "0xB4FF00FF",
        "0x40022080": "0xC0000000",
        "0x400220E0": "0x00170000",
        "0x400221E0": "0x0000007F",
        "0x40022070": "0xFFFFFFF8",
        "0x40022170": "0xFFFFFFFF",
        "0x400220F0": "0x00130000",
        "0x400221F0": "0x0000007F",
        "0x40022090": "0xB4FF00FF",
        "0x400220C0": "0xED0000FF",
    }

    script_content = [
        "// Option Bytes Programming Script",
        "// Generated by provision_jlink.py",
        "",
        "// Connect to device",
        "connect",
        "",
        "// Unlock option bytes",
        "w4 0x40022008 0x08192A3B",
        "w4 0x40022008 0x4C5D6E7F",
        "",
        "// Wait for option bytes unlock",
        "sleep 100",
        "",
        "// Write option bytes to option byte registers",
    ]

    for addr, value in ob_config.items():
        script_content.append(f"w4 {addr} {value}")

    script_content.extend([
        "",
        "// Start option bytes programming",
        "w4 0x40022004 0x00020000",
        "",
        "// Wait for programming to complete",
        "sleep 1000",
        "",
        "// Lock option bytes",
        "w4 0x40022004 0x40000000",
        "",
        "// Reset to apply option bytes",
        "r",
        "sleep 500",
        "",
        "exit"
    ])

    script_path = JLINK_SCRIPTS_DIR / "set_option_bytes.jlink"
    with open(script_path, 'w') as f:
        f.write('\n'.join(script_content))

    print(f"Generated option bytes script: {script_path}")

def main():
    input("Set BOOT0=1. Press Enter to continue...")
    if not program_obkeys_with_devpro(DEVPRO_EXE):
        print_error("OBK provisioning failed with DevPro")
        sys.exit(1)

    print("OBK provisioning complete")

    print("STEP 3: Set BOOT0=0")
    input("Please disconnect BOOT0 from VDD (STM32H573I-DK: set SW1 to position 0). Press Enter to continue...")

    print("STEP 4: Reset & Halt MCU")
    if not run_jlink_script("reset_halt.jlink", "Resetting and halting MCU"):
        print_error("Failed to reset and halt MCU")
        sys.exit(1)

    print("STEP 5: Program Bootloader and Application")
    generate_flash_script()
    if not run_jlink_script("flash_images.jlink", "Programming bootloader and application"):
        print_error("Failed to program flash images")
        sys.exit(1)

    print("STEP 6 & 7: Program Option Bytes and Product State")
    generate_option_bytes_script()
    if not run_jlink_script("set_option_bytes.jlink", "Programming option bytes and product state"):
        print_error("Failed to program option bytes")
        sys.exit(1)

    print("Provisioning Complete")
    print("The board is correctly configured.")
    print("Connect UART console (115200 baudrate) to get application menu.")

def generate_flash_script():
    img_config_path = OEMIROT_DIR / "img_config.sh"
    app_image_number = 1
    app_full_secure = False

    if img_config_path.exists():
        with open(img_config_path, 'r') as f:
            content = f.read()
            if 'app_image_number=2' in content:
                app_image_number = 2
            if 'app_full_secure=1' in content:
                app_full_secure = True

    script_content = [
        "// Flash Programming Script",
        "// Generated by provision_jlink.py",
        "",
        "// Connect to device",
        "connect",
        "",
        "// Halt CPU",
        "halt",
        "",
    ]

    boot_addr = "0x0C000000"
    if OEMIROT_BOOT_BIN.exists():
        script_content.append(f"// Program OEMiROT_Boot at {boot_addr}")
        script_content.append(f"loadbin {OEMIROT_BOOT_BIN} {boot_addr}")
        script_content.append("")
    else:
        print_error(f"Bootloader binary not found: {OEMIROT_BOOT_BIN}")

    if app_image_number == 1:
        if app_full_secure:
            app_hex = APPLI_DIR / "Binary/rot_tz_s_app_init_sign.hex"
        else:
            app_hex = APPLI_DIR / "Binary/rot_tz_app_init_sign.hex"

        if app_hex.exists():
            script_content.append(f"// Program Application")
            script_content.append(f"loadfile {app_hex}")
            script_content.append("")
        else:
            print_error(f"Application hex not found: {app_hex}")
    else:
        s_app_hex = APPLI_DIR / "Binary/rot_tz_s_app_init_sign.hex"
        ns_app_hex = APPLI_DIR / "Binary/rot_tz_ns_app_init_sign.hex"

        if s_app_hex.exists():
            script_content.append(f"// Program Secure Application")
            script_content.append(f"loadfile {s_app_hex}")
            script_content.append("")
        else:
            print_error(f"Secure application hex not found: {s_app_hex}")

        if ns_app_hex.exists():
            script_content.append(f"// Program Non-Secure Application")
            script_content.append(f"loadfile {ns_app_hex}")
            script_content.append("")
        else:
            print_error(f"Non-secure application hex not found: {ns_app_hex}")

    script_content.extend([
        "// Verify programming",
        "verifybin {OEMIROT_BOOT_BIN} {boot_addr}",
        "",
        "exit"
    ])

    script_text = '\n'.join(script_content)
    script_text = script_text.replace('{OEMIROT_BOOT_BIN}', str(OEMIROT_BOOT_BIN))
    script_text = script_text.replace('{boot_addr}', boot_addr)

    script_path = JLINK_SCRIPTS_DIR / "flash_images.jlink"
    with open(script_path, 'w') as f:
        f.write(script_text)

    print(f"Generated flash programming script: {script_path}")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nProvisioning aborted by user")
        sys.exit(1)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
